### PR TITLE
fix component depends and add the ignore file

### PR DESCRIPTION
**Pull request by gagaboy**
Fix component depends with udm and usl component, and add the ignore file

### CODE REVIEW

**Comment by jonesde** [comment]
There are 2 sections to add yourself to in the AUTHORS file. I apologize for the bother. One thing that makes it a little easier: after you push a commit to your fork for this pull request you can update the pull request instead of creating a new one.

**Comment by gagaboy** [comment]
Well,I'm not sure to add myself to which AUTHORS file and is this commit ok?

**Comment by jonesde** [comment]
The line you added after line 59 is great (the patent part), a line just like that is needed after line 37 as well (the CC0 part).

**Comment by gagaboy** [comment]
ok,I have updated this pull request

**Comment by jonesde** [comment]
Thank you Eric, looks good.

**Pull request merged**
